config/routes.rb
Rails.application.routes.draw do
  
   root 'users#index'
   get '/index'=>'users#index' ,as: 'home'
   get '/admin' => 'admin#index', as: 'admin'
   get '/signup' => 'users#signup', as: 'signup'
   get '/login' => 'users#login', as: 'login'
   get '/appointment' => 'users#appointment', as: 'appointment'
   get '/cancel' => 'users#cancel', as: 'cancel'
   get '/logout' => 'users#logout', as: 'logout'
   get '/status' => 'admin#status', as: 'status'
   get '/status_done/:id' => 'admin#status_done', as: 'status_done'
   get '/appointmentdelete/:id' => 'users#appointmentdelete', as: 'appointmentdelete'
   get '/patch/:id'=>'admin#patch' ,as: 'patch'
   get '/edit/:id'=>'admin#edit' ,as: 'edit'
   patch '/doctors/:id'=>'admin#update',as: 'doctor'
   delete '/delete/:id'=>'admin#delete' ,as: 'delete'
   get '/register' => 'users#register'
   post '/register' => 'users#register'
   post '/order' => 'users#order'
   post '/new' => 'admin#new'
   get '/add' => 'admin#add'
   get '/new' => 'admin#index'
   post '/attempt_login' => 'admin#attempt_login'
   post '/attempt_ulogin' => 'users#attempt_ulogin'
   post '/forgot_form' => 'users#forgot_form'
   get '/forgot' => 'users#forgot'
   post '/add_slot' => 'admin#add_slot'
   post '/book_slot' => 'users#book_slot'
   get '/confirm' => 'users#confirm'
   resources :users
    resources :account_activations, only: [:edit]
   
   #resources :doctors
   match ':controller(/:action(/:id(.:format)))', :via => [:get,:post]
end

app/views/admin/_flash_messages.html.erb
<% flash.each do |name, msg| %>
<center>
<div class='alert alert-<%=name %>'>
	<%= msg %>
</div>
</center>
<% end %>

app/views/admin/add.html.erb
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>MAHC</title>
	<meta charset="UTF-8">
	<meta name="description" content="Instyle Fashion HTML Template">
	<meta name="keywords" content="instyle, fashion, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="assets/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="css/slicknav.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>
	<style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
 
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
  }
}
</style>

</head>
<body>


  <!-- header section -->
  <header >
    <nav class="navbar navbar-expand-md  ">
                <div class="container">
                    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item active"><%= link_to "Requests", status_path %></li>                       
                            <li class="nav-item"><%= link_to "Log out", logout_path %></li>
                        </ul>                       
                    </div>
                </div>
    </nav>
  </header>
  <!-- header section end -->
  
  <p class="main-text">Logged In as:<span style="color: red"> Admin</span></p>
	
  <div class="row">
    <div class="col-xs-7 col-sm-7">
        
        <h4><center class="main-text">Available Slots</center></h4>
        <br>
        <div class="well">         
            <table class="table table-striped">
                <tr>
                  <th>Slot_name</th>               
                  <th> Options</th>
                </tr>
                <% @temp = Doctor.all.order("slot_name ASC")%>
                <% @temp.each do |slot| %>
                  <tr>
                    <td><%= slot.slot_name %></td>                
                    <td ><%= link_to 'Cancel',delete_path(slot),method: :delete, class:'btn btn-danger' ,data: { confirm: 'Are you sure?' } %></td>
                    
                  </tr>
                <% end %>
            </table>
        </div>
    </div>
    <div class="col-xs-5 col-sm-5">
      
      <%= render 'flash_messages' %>
      <center class="main-text"><h4>Add Slot</h4></center>
      <br>
      <div class="well">
          <%= form_with scope: :doctor, local: true, url:'/add_slot' do |form| %>
            <% if @doctor.errors.any? %>
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@doctor.errors.count, "error") %> Errors
                </h3>
                <ul>
                  <% @doctor.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
							<%= form.label :Slot_name %>
							<%= form.text_field :slot_name, class:'form-control' %>
						</div>
            <%= form.submit 'Submit', class:'btn btn-primary btn-block' %>
          <% end %>
      </div>
    </div>
  </div>

  <%= render 'partials/footer' %>
  



<!--Table Listing-->
  
	
	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/circle-progress.min.js"></script>
	<script src="js/main.js"></script>



	</body>
</html>

app/views/admin/edit.html.erb
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>MAHC</title>
	<meta charset="UTF-8">
	<meta name="description" content="Instyle Fashion HTML Template">
	<meta name="keywords" content="instyle, fashion, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="assets/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="css/slicknav.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>


	<!-- header section -->
	<header class="header-section">
		<div class="header-warp">
			<!--%= link_to image_tag("logo.png"), home_path %-->
                           <%= ADMIN%>
			<ul class="main-menu">
				<li><%= link_to 'home',home_path%></li>
				<li><%= link_to 'logout','admin/logout'%></li>
				<!--<li><%= link_to 'appointment',appointment_path%></li>
				<li><%= link_to 'cancel',cancel_path%></li>-->
			</ul>
		</div>
	</header>
	<!-- header section end -->
	<%= render 'flash_messages' %>
	
	<h4><center>Edit Slots</center></h4>
    <br>
    <div align="center">
	<%= form_with model: @edit, local: true do |form| %>
	<% if @edit.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@edit.errors.count, "error") %> Errors
      </h3>
      <ul>
        <% @edit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	
  <p>
    <b>Slot_name </b>
    &nbsp;&nbsp;&nbsp;
    <%= form.text_field :slot_name %>
</p>


    <%= form.submit 'Submit'%>
  </p>
</p>
<% end %>

  
	
	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/circle-progress.min.js"></script>
	<script src="js/main.js"></script>



	</body>
</html>

app/views/admin/index.html.erb
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>MAHC</title>
		<meta charset="UTF-8">
		<meta name="description" content="Instyle Fashion HTML Template">
		<meta name="keywords" content="instyle, fashion, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Favicon -->
		<link href="assets/favicon.ico" rel="shortcut icon"/>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

		<!-- Stylesheets -->
		<link rel="stylesheet" href="css/bootstrap.min.css"/>
		<link rel="stylesheet" href="css/font-awesome.min.css"/>
		<link rel="stylesheet" href="css/owl.carousel.min.css"/>
		<link rel="stylesheet" href="css/slicknav.min.css"/>

		<!-- Main Stylesheets -->
		<link rel="stylesheet" href="css/style.css"/>


		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>


		<!-- header section -->
		<%= render 'partials/header' %>
		<!-- header section end -->

		<%= render 'flash_messages' %>

		<center>
			<h3>AdminLogin</h3><br>
			<div class="container">
				<%= form_with scope: :adminlogin, local: true, class: 'form-signin', url:'/attempt_login' do |form| %>				
					<%= form.text_field :adminid, class:'form-control',placeholder:'UserName' %>
			
					<%= form.password_field :password, class:'form-control',placeholder:'Password' %> 
			
					<%= submit_tag "Login", class:'btn btn-lg btn-primary btn-block'%>
				<% end %>
			</div>
		</center>

		<%= render 'partials/footer' %>
		
		<!--====== Javascripts & Jquery ======-->
		<script src="js/jquery-3.2.1.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.slicknav.min.js"></script>
		<script src="js/owl.carousel.min.js"></script>
		<script src="js/circle-progress.min.js"></script>
		<script src="js/main.js"></script>



	</body>
</html>

app/views/admin/status.html.erb
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>MAHC</title>
	<meta charset="UTF-8">
	<meta name="description" content="Instyle Fashion HTML Template">
	<meta name="keywords" content="instyle, fashion, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="assets/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="css/slicknav.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>


	<!-- header section -->
	<header >
    <nav class="navbar navbar-expand-md  ">
                <div class="container">
                    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item active"><%= link_to "Requests", status_path %></li> 
                                <li class="nav-item"><%= link_to 'Add Slot',add_path%></li>                      
                            <li class="nav-item"><%= link_to "Log out", logout_path %></li>
                           
                        </ul>                       
                    </div>
                </div>
    </nav>
  	</header>
	<!-- header section end -->
	<p class="main-text">Logged In as:<span style="color: red"> Admin</span></p>
	<%= render 'flash_messages' %>
	<div class="container">
		
		<center><h3><b>Patient's Request List</b></h3></center><br>    
		<div class="well">        
			<table class="table table-striped">
				<tr>
					<!--th>Patient Id</th-->
					<th>Patient Name</th>
					<th>Slot Name</th>
					<th>Date of  Appointment</th>
					<th>Status</th>
				</tr>
				<% temp = Appointment.all %>
				<% temp.each do |user| %>
				<tr>
					<!--td><%= user.pid %></td--> 	
					<td><%= user.p_name %></td>
					<td><%= user.slot_name %></td>
					<td><%= user.doa %></td>
					<td><%= link_to 'Confirm Request',status_done_path(user) ,
						data: { confirm: 'Confirm Request and Send Confirmation Mail' } %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
	<!--Table Listing-->

	<%= render 'partials/footer' %>

	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/circle-progress.min.js"></script>
	<script src="js/main.js"></script>



	</body>
</html>