config/routes.rb
Rails.application.routes.draw do
  
   root 'users#index'
   get '/index'=>'users#index' ,as: 'home'
   get '/admin' => 'admin#index', as: 'admin'
   get '/signup' => 'users#signup', as: 'signup'
   get '/login' => 'users#login', as: 'login'
   get '/appointment' => 'users#appointment', as: 'appointment'
   get '/cancel' => 'users#cancel', as: 'cancel'
   get '/logout' => 'users#logout', as: 'logout'
   get '/status' => 'admin#status', as: 'status'
   get '/status_done/:id' => 'admin#status_done', as: 'status_done'
   get '/appointmentdelete/:id' => 'users#appointmentdelete', as: 'appointmentdelete'
   get '/patch/:id'=>'admin#patch' ,as: 'patch'
   get '/edit/:id'=>'admin#edit' ,as: 'edit'
   patch '/doctors/:id'=>'admin#update',as: 'doctor'
   delete '/delete/:id'=>'admin#delete' ,as: 'delete'
   get '/register' => 'users#register'
   post '/register' => 'users#register'
   post '/order' => 'users#order'
   post '/new' => 'admin#new'
   get '/add' => 'admin#add'
   get '/new' => 'admin#index'
   post '/attempt_login' => 'admin#attempt_login'
   post '/attempt_ulogin' => 'users#attempt_ulogin'
   post '/forgot_form' => 'users#forgot_form'
   get '/forgot' => 'users#forgot'
   post '/add_slot' => 'admin#add_slot'
   post '/book_slot' => 'users#book_slot'
   get '/confirm' => 'users#confirm'
   resources :users
    resources :account_activations, only: [:edit]
   
   #resources :doctors
   match ':controller(/:action(/:id(.:format)))', :via => [:get,:post]
end

app/models/user.rb
class User < ApplicationRecord
     
       attr_accessor :remember_token, :activation_token
                before_save :downcase_email
                before_create :create_activation_digest
         

	has_secure_password
	validates :p_id, :name, :dob, :phone, :address,:password,:email,:confirm_password,:presence => true
	validates :p_id, :length => { :minimum => 3}
	validates :password,:confirm_password, :length => {:minimum => 5}
	validates :phone, length: { is: 10 }
	validates :phone, numericality: { only_integer: true }
	validates :p_id, :phone,:email, uniqueness: true
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
        # Creates and assigns the activation token and digest.
            def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
             end
            def downcase_email
              self.email = email.downcase
             end
              def User.new_token
                 SecureRandom.urlsafe_base64
                end
                def User.digest(string)
                   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
                    BCrypt::Password.create(string, cost: cost)
                end
                    def authenticated?(attribute, token)
                   digest = send("#{attribute}_digest")
                       return false if digest.nil?
                          BCrypt::Password.new(digest).is_password?(token)
                         end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	add_flash_types :danger,:info, :success,:warning
	before_action :confirm_logged_in, :except =>[:index,:forgot_p_id,:forgot,:signup,:show,:login,:attempt_ulogin,:logout,:validate,:register,:forgot_form]
	def index
		@users= User.all
	end
	def forgot

		
	end
	def appointmentdelete
    @order = Appointment.find(params[:id])
    @slot = Doctor.find_by(slot_name: @order.slot_name)
    ###########################################################################################
  

    	@order.destroy
    	redirect_to appointment_path(session[:p_id])
   	
  	end
	def forgot_form
		@mail = forgotparams[:email]
		@fuser = User.where(:email => @mail).first
		if @fuser==nil
			redirect_to forgot_path, danger: "Email_id not found in users list!!"
		else
			UserMailer.forgot(@fuser).deliver_now
			redirect_to login_path, info: "Check your email for login credentials #{@fuser.name}"
		end

	end
	def signup
	 @user = User.new
 
              

      
          end
    def show
		redirect_to signup_path, success: "User Account Activated Succesfully!!"
	end
	def appointment
		ptid = session[:p_id]
		@appointment=Appointment.new
		@buser = User.where(:p_id => ptid).first
		
      		@temp= Appointment.where(:pid=> session[:p_id])
      		@temp.each do |list|
      			
      		end
      		
	
	end
##################BOOK Appointment


	def book_slot
	@buser = User.where(:p_id => session[:p_id]).first
            
    @appointment=Appointment.new(appointmentparams)
            ##############
                    if Date.today>=@appointment.doa || @appointment.p_name==nil
                        flash[:danger] = "Appointment Not requested Try again"
                        @appointment.destroy
   			redirect_to appointment_path(session[:p_id])
             ##################
                        else
                              username = session[:p_id]
                              found_user = User.where(:p_id => username).first
                                 found_slot = Doctor.where(:slot_name => @appointment.slot_name).first
                    if found_user # taking email in phone column
   @appointment.update_attributes(:pid => found_user.p_id ,:p_name =>  @appointment.p_name,:phone =>  found_user.email,:doa =>@appointment.doa)
 
      if @appointment.save
      
    	found_slot1 = Doctor.where(:slot_name => @appointment.slot_name).first
      		redirect_to appointment_path(session[:p_id]), success: "Appointment  Requested Successfully, You will get E-mail when your request will get accepted!! "
      	else
      		@appointment.destroy
      		redirect_to appointment_path(session[:p_id]), warning: "Appointment was not requested successfully!!"
   
      
        render '/users/appointment'
      end 
    else
      flash[:danger] = "Please try again!!"
      render '/users/appointment'
    end
    end

  end
	def login

	end
	

 def attempt_ulogin   
  	username=uloginparams[:p_id]
  	password=uloginparams[:password]
  	if username.present? && password.present?
               found_user = User.where(:p_id => username).first
               if found_user && found_user.activated?
                     authorized_user = found_user.authenticate(uloginparams[:password])
                                           if authorized_user
                                                 # TODO: mark user as logged in
                                                 session[:user_id]=authorized_user.id
                                                     session[:p_id]=authorized_user.p_id
                                                      redirect_to  appointment_path(session[:p_id]),success: "Hi #{session[:p_id]}"
                                               else
                                                       redirect_to login_path, danger: "Invalid Login Credentials!!"
                                               end
               else
                    message = "User Not Found or Account not activated. "
                    message += "Check your email for the activation link."
                    flash[:warning] = message
                    redirect_to root_url
             end
        end
  
  end
  
  def logout
    session[:user_id]=nil
    session[:p_id]=nil
    redirect_to home_path,info: "Logged out!!"
  end
  def confirm
    ptid = session[:p_id]
    @fuser = User.where(:p_id => ptid).first
    @mail = @fuser.email
    if @fuser==nil
      redirect_to home_path, danger: "Invalid Credentials!!"
    else
      redirect_to appointment_path(session[:p_id]), success: "You will get E-mail when your request will get accepted!!"
    end
  end
	def cancel

	end
	
	def register
                                    
		@user=User.new(regparams)
                    if Date.today-@user.dob<18
                        flash[:danger] = "User must be atleast 12 years old!!"
   			render 'signup'
                   else
                        
		   if @user.password==@user.confirm_password 
			if @user.save
    		          #redirect_to @user

                          UserMailer.account_activation(@user).deliver_now
                             flash[:info] = "Please check your email to activate your account."
                                 redirect_to root_url
                                    
  			    else
   				render 'signup'
   			end
   		else
   			flash[:danger] = "password & confirm_password doesn't match!!"
   			render 'signup'
   		end
             end

	end
	
	private
	def regparams
		params.require(:user).permit(:p_id, :name, :dob, :gender, :phone, :address, :password,:email,:confirm_password)
	end
	def validateparams
		params.require(:valid).permit(:cid)
	end
	def uloginparams
		params.require(:ulogin).permit(:p_id,:password)
	end
	def forgotparams
		params.require(:forgot).permit(:email)
	end
	 def appointmentparams
    params.require(:book_slots).permit(:p_name,:slot_name,:doa)
  	end
	private
	def confirm_logged_in
		unless session[:user_id]
			redirect_to home_path, warning: "Please Login!!"
			return false
		else
			return true
		end
	end
end

app/helpers/users_helper.rb
module PostsHelper
end

app/views/users/_flash_messages.html.erb
<% flash.each do |name, msg| %>
<center>
<div class='alert alert-<%=name %>'>
	<%= msg %>
</div>
</center>
<% end %>

app/views/users/appointment.html.erb
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>MAHC</title>
		<meta charset="UTF-8">
		<meta name="description" content="Instyle Fashion HTML Template">
		<meta name="keywords" content="instyle, fashion, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Favicon -->
		<link href="assets/favicon.ico" rel="shortcut icon"/>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

		<!-- Stylesheets -->
		<link rel="stylesheet" href="css/bootstrap.min.css"/>
		<link rel="stylesheet" href="css/font-awesome.min.css"/>
		<link rel="stylesheet" href="css/owl.carousel.min.css"/>
		<link rel="stylesheet" href="css/slicknav.min.css"/>

		<!-- Main Stylesheets -->
		<link rel="stylesheet" href="css/style.css"/>
		<style>
	* {
	box-sizing: border-box;
	}

	/* Create two equal columns that floats next to each other */
	.column {
	float: left;
	width: 50%;
	padding: 10px;
	
	}

	/* Clear floats after the columns */
	.row:after {
	content: "";
	display: table;
	clear: both;
	}

	/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
	@media screen and (max-width: 600px) {
	.column {
		width: 100%;
	}
	}
	</style>

		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>
		<!-- header section -->
		<header >
			<nav class="navbar navbar-expand-md  ">
						<div class="container">
							<div class="collapse navbar-collapse" id="navbarsExampleDefault">
								<ul class="nav navbar-nav mr-auto">							
									<li class="nav-item"><%= link_to "Log out", logout_path %></li>
								</ul>                       
							</div>
						</div>
			</nav>
		</header>
		<!-- header section end -->  

		<p class="main-text">Logged In as:<span style="color: red"> <%= @buser.name %></span></p>

		<%= render 'flash_messages' %>                    
		<div class="row">
			<div class="col-xs-5 col-sm-5">
				<div class="well">
					<h1>New Appointment</h1>

					<%= form_with scope: :book_slots, local: true, url:'/book_slot' do |form| %>
						<ul>
							<% @appointment.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>

						<div class="form-group">
							<%= form.label :Patient_Name %>
							<%= form.text_field :p_name, class:'form-control' %>
						</div>

						<div class="form-group">
							<%= form.label :Date %>
							<%= form.date_select :doa, class:'form-control' %>
						</div>

						<div class="form-group">
							<%= form.label :Slot %>
							<%= form.collection_select(:slot_name, Doctor.all, :id, :slot_name, {:prompt => 'Select the Slot'}, :selected => @appointment.slot_name , class:'form-control') %>
						</div>
						<%= @appointment.slot_name %>
						
						<%= submit_tag "Request!", class:'btn btn-primary btn-block'%>
					<% end %>
						
				</div>
			</div>
			<div class="col-xs-7 col-sm-7">
				<div class="well">
					<h2 class="page-header">Appointments</h2>
						<table class="table table-striped">
							<tr>
								<th>Patient name</th>
								<th>Date</th>
								<th>Slot</th>
								<th colspan="14"></th>
							</tr>
							<% @order_user = Appointment.where(:pid => @buser.p_id) %> 
							<% @order_user.all.each do |slot| %>
								<tr>
									<td ><%= slot.p_name %></td>
									<td ><%= slot.doa %></td>
									<td ><%= slot.slot_name %></td>												
									<td ><%= link_to 'Cancel',appointmentdelete_path(slot), class:'btn btn-danger' ,data: { confirm: 'Are you sure?' } %></td>
								</tr>
							<% end %>
						</table>
					<br>
				</div>
			</div>
		</div>
		

		<%= render 'partials/footer' %>
		
		<!--button type="button" class="btn btn-link"><%= link_to 'Confirm Request','/confirm'%></button>
		<!--====== Javascripts & Jquery ======-->
		<script src="app/javascript/jquery-3.2.1.min.js"></script>
		<script src="app/javascript/bootstrap.min.js"></script>
		<script src="app/javascript/jquery.slicknav.min.js"></script>
		<script src="app/javascript/owl.carousel.min.js"></script>
		<script src="app/javascript/circle-progress.min.js"></script>
		<script src="app/javascript/main.js"></script>



	</body>
</html>

app/views/users/forgot.html.erb
<!DOCTYPE html>
<html lang="zxx">
<head>
  <title>MAHC</title>
  <meta charset="UTF-8">
  <meta name="description" content="Instyle Fashion HTML Template">
  <meta name="keywords" content="instyle, fashion, html">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- Favicon -->
  <link href="assets/favicon.ico" rel="shortcut icon"/>

  <!-- Google font -->
  <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="css/bootstrap.min.css"/>
  <link rel="stylesheet" href="css/font-awesome.min.css"/>
  <link rel="stylesheet" href="css/owl.carousel.min.css"/>
  <link rel="stylesheet" href="css/slicknav.min.css"/>

  <!-- Main Stylesheets -->
  <link rel="stylesheet" href="css/style.css"/>
<!-- listing table -->

  

</head>
<body>
  <!-- header section -->
  <header class="header-section">
    <div class="header-warp">
      <%= "Make Request" %>
      <ul class="main-menu">
        <li><%= link_to 'home',home_path%></li>
        <li><%= link_to 'admin',admin_path%></li>
        <li><%= link_to 'signup',signup_path%></li>
        <li><%= link_to 'login',login_path%></li>
        
      </ul>
    </div>
  </header>
  <!-- header section end --> 
  <!-- listing table-->

<%= render 'flash_messages' %>  
 

<br>
<br><br><br><br>
<div align="center">
	<%= form_with scope: :forgot, local: true, url:'/forgot_form' do |form| %>
  <p>
    <b>Email_id</b>
    &nbsp;&nbsp;&nbsp;
    <%= form.text_field :email %>
  </p>
    <%= submit_tag "Send me Credentials" %>
  <% end %>
</div>
 <!--====== Javascripts & Jquery ======-->
  <script src="js/jquery-3.2.1.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.slicknav.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/circle-progress.min.js"></script>
  <script src="js/main.js"></script>


  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>MAHC</title>
	<meta charset="UTF-8">
	<meta name="description" content="Instyle Fashion HTML Template">
	<meta name="keywords" content="instyle, fashion, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="assets/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="css/slicknav.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>
<!-- listing table -->
	

</head>
<body>
	<!-- header section -->
		<%= render 'partials/header' %>
	<!-- header section end -->	
	<%= render 'flash_messages' %>
  <div class="centered" align="center">
  	<h2 >Managing Appointments At Health Centre</h2>
  	<button onclick="location.href = '/login';" type="button" class="btn btn-link" style><h6><u>Request Appointment Online</u></h6></button><br><h6>FOR HELP</h6><br><h2 >Call Us @ 721000000</h2><br>
<h4>Address: NITC</h4>
  	
  </div>
  <br>   
</div> 

	<%= render 'partials/footer' %>

	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.slicknav.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/circle-progress.min.js"></script>
	<script src="js/main.js"></script>


	</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>MAHC</title>
		<meta charset="UTF-8">
		<meta name="description" content="Instyle Fashion HTML Template">
		<meta name="keywords" content="instyle, fashion, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Favicon -->
		<link href="assets/favicon.ico" rel="shortcut icon"/>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

		<!-- Stylesheets -->
		<link rel="stylesheet" href="css/bootstrap.min.css"/>
		<link rel="stylesheet" href="css/font-awesome.min.css"/>
		<link rel="stylesheet" href="css/owl.carousel.min.css"/>
		<link rel="stylesheet" href="css/slicknav.min.css"/>

		<!-- Main Stylesheets -->
		<link rel="stylesheet" href="css/style.css"/>


		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>


		<!-- header section -->
		<%= render 'partials/header' %>
		<!-- header section end -->

		<%= render 'flash_messages' %>

		<center>
			<h3>Enter Credentials for Login</h3><br>
			<div class="container">
				<%= form_with scope: :ulogin, local: true,class: 'form-signin', url:'/attempt_ulogin' do |form| %>
					<%= form.text_field :p_id, class:'form-control',placeholder:'UserName' %>

					<%= form.password_field :password, class:'form-control',placeholder:'Password' %> 

					<%= submit_tag "Login", class:'btn btn-lg btn-primary btn-block'%>
					<br>
					<%= link_to 'forgot-password/UserName?','/forgot'%><br>
				<% end %>
			</div>
		</center>

		<%= render 'partials/footer' %>
	
		
		<!--====== Javascripts & Jquery ======-->
		<script src="app/javascript/jquery-3.2.1.min.js"></script>
		<script src="app/javascript/bootstrap.min.js"></script>
		<script src="app/javascript/jquery.slicknav.min.js"></script>
		<script src="app/javascript/owl.carousel.min.js"></script>
		<script src="app/javascript/circle-progress.min.js"></script>
		<script src="app/javascript/main.js"></script>



	</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>MAHC</title>
		<meta charset="UTF-8">
		<meta name="description" content="Instyle Fashion HTML Template">
		<meta name="keywords" content="instyle, fashion, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <!-- header section -->
        <header >
            <nav class="navbar navbar-expand-md  ">
                        <div class="container">
                            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                                <ul class="nav navbar-nav mr-auto">
                                    <li class="nav-item active"><%= link_to "Home", home_path %></li>
                                    <li class="nav-item"><%= link_to "Admin", admin_path %></li>							
                                    <li class="nav-item"><%= link_to "Log out", logout_path %></li>
                                </ul>                       
                            </div>
                        </div>
            </nav>
        </header>
        <!-- header section end -->  

        <p class="main-text">Logged In as:<span style="color: red"> <%= @buser.name %></span></p>

        <%= render 'flash_messages' %>
        <div class="well">
            <h1>New Appointment</h1>

            <%= form_with scope: :book_slots, local: true, url:'/book_slot' do |form| %>
                <ul>
                    <% @appointment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                </ul>

                <div class="form-group">
                    <%= form.label :Patient_Name %>
                    <%= form.text_field :p_name, class:'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :Date %>
                    <%= form.date_select :doa, class:'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :Slot %>
                    <%= form.collection_select(:slot_name, Doctor.all, :id, :slot_name, {:prompt => 'Select the Slot'}, :selected => @appointment.slot_name , class:'form-control') %>
                </div>
                <%= @appointment.slot_name %>
                
                <%= submit_tag "Request!" %>
            <% end %>
                

            <%= link_to 'Back', appointment_path %>
        </div>

		
		<!--button type="button" class="btn btn-link"><%= link_to 'Confirm Request','/confirm'%></button>
		<!--====== Javascripts & Jquery ======-->
		<script src="app/javascript/jquery-3.2.1.min.js"></script>
		<script src="app/javascript/bootstrap.min.js"></script>
		<script src="app/javascript/jquery.slicknav.min.js"></script>
		<script src="app/javascript/owl.carousel.min.js"></script>
		<script src="app/javascript/circle-progress.min.js"></script>
		<script src="app/javascript/main.js"></script>

	</body>
</div>

app/views/users/signup.html.erb
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>MAHC</title>
		<meta charset="UTF-8">
		<meta name="description" content="Instyle Fashion HTML Template">
		<meta name="keywords" content="instyle, fashion, html">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Favicon -->
		<link href="assets/favicon.ico" rel="shortcut icon"/>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i&display=swap" rel="stylesheet">

		<!-- Stylesheets -->
		<link rel="stylesheet" href="css/bootstrap.min.css"/>
		<link rel="stylesheet" href="css/font-awesome.min.css"/>
		<link rel="stylesheet" href="css/owl.carousel.min.css"/>
		<link rel="stylesheet" href="css/slicknav.min.css"/>

		<!-- Main Stylesheets -->
		<link rel="stylesheet" href="css/style.css"/>
	</head>

	<body>

		<!-- header section -->
			<%= render 'partials/header' %>
		<!-- header section end -->

		<%= render 'flash_messages' %>

		<center>
		<h3>Enter Your Details</h3><br>
		
			
		<!-- forms--> 
		<div class="container1">
			<%= form_with scope: :user, local: true, url:'/register' do |form| %>
				<% if @user.errors.any? %>
					<div id="error_explanation">
						<h3>
							<%= pluralize(@user.errors.count, "error") %> Errors
						</h3>
						<ul>
							<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				
				<div class="form-group">
					<%= form.text_field :p_id, class:'form-control',placeholder:'UserName' %>
				</div>
				<div class="form-group">
					<%= form.text_field :name, class:'form-control',placeholder:'Full Name' %>
				</div>
				<div class="form-group">
					<%= form.text_field :email, class:'form-control',placeholder:'Email Id' %>
				</div>
				<div class="form-group">
					<%= form.password_field :password, class:'form-control',placeholder:'Password' %>
				</div>
				<div class="form-group">
					<%= form.password_field :confirm_password, class:'form-control',placeholder:'Confirm Password' %>
				</div>
				<div class="form-group">
					<%= form.label :DOB, class:'main-text'%>
					<%= form.date_field :dob, class:'form-control' %>
				</div>
				<div class="form-group">
					<%= form.label :Gender, class:'main-text'%>
					<%= form.text_field :gender, class:'form-control' %>
				</div>			
				<div class="form-group">
					<%= form.text_field :phone, class:'form-control',placeholder:'Phone' %>
				</div>			
				<div class="form-group">
					<%= form.text_area :address, class:'form-control',placeholder:'Address' %>
				</div>
				
				<%= form.submit 'Submit', class:'btn btn-lg btn-primary btn-block' %>
			<% end %>
		</div>
		</center>

		<%= render 'partials/footer' %>
		
		<!--end -->
		<!--====== Javascripts & Jquery ======-->
		<script src="js/jquery-3.2.1.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.slicknav.min.js"></script>
		<script src="js/owl.carousel.min.js"></script>
		<script src="js/circle-progress.min.js"></script>
		<script src="js/main.js"></script>

	</body>
</html>